### ISSUE TITLE
Switching from empty family tree to example.gramps ( AttributeError: 'NoneType' object has no attribute 'get_family_handle_list' )

### ISSUE THREAD

**Issue by giotodibondone** [ztlxltl/FamilyTreeView#6]
In a clean copy of gramps 5.2.3 on win 10 VM (virtualbox)

If I start with an empty family tree then open the [example.gramps](https://gramps-project.org/wiki/index.php?title=Example.gramps) family tree I get:

> 2024-12-26 08:27:08.360: WARNING: dummydb.py: line 799: handle  does not exist in the dummy database
> Warning: DbState: Exception occurred in callback function.
> Traceback (most recent call last):
>   File "C:\Program Files\GrampsAIO64-5.2.3\gramps\gen\utils\callback.py", line 424, in emit
>     fn(*args)
>   File "C:\Users\admin\AppData\Local\gramps\gramps52\plugins\FamilyTreeView\family_tree_view.py", line 167, in _cb_db_changed
>     self.close_info_and_rebuild()
>   File "C:\Users\admin\AppData\Local\gramps\gramps52\plugins\FamilyTreeView\family_tree_view.py", line 206, in close_info_and_rebuild
>     self.rebuild_tree()
>   File "C:\Users\admin\AppData\Local\gramps\gramps52\plugins\FamilyTreeView\family_tree_view.py", line 219, in rebuild_tree
>     self.widget_manager.tree_builder.process_person(root_person_handle, 0, 0, ahnentafel=1)
>   File "C:\Users\admin\AppData\Local\gramps\gramps52\plugins\FamilyTreeView\family_tree_view_tree_builder.py", line 89, in process_person
>     family_handles = person.get_family_handle_list()
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'get_family_handle_list'
> 

Same thing happens 
* if you start gramps with example.gramps then switch to the empty family tree.
* if you start gramps with example.gramps then bring up the "Family Trees" (manager dialog) and select "Close" for the family tree ( not the manager dialog)

**Comment by emyoulation** [comment]
The dummy.db occurs when no tree is loaded.

It is a momentary condition while gramps is started before previous session's tree is loaded. It also occurs when switching trees, while the current tree is unloaded and before the new tree is loaded.

The condition can be longer... if the active tree is unloaded or the Family Tree selector is dismissed without loading any Tree.

If this View REQUIRES more content than the dummy.db provides (like an Active Person or a Home Person) then is needs to be able to recognize the condition is not fulfilled and handle with error handling.

https://github.com/gramps-project/gramps/blob/master/gramps/gen/db/dummydb.py

**Comment by emyoulation** [comment]
the Beta What's Next addon dashboard gramplet (available through Addon Manager) has sample code to recognize:
1) no database loaded
2) no people
3) no active person
4) no home person

https://github.com/gramps-project/addons-source/blob/maintenance/gramps52/Betawhatsnext/Betawhatsnext.py

**Comment by emyoulation** [comment]
If your view provides any feedback for these conditions (or better yet, a GUI option for an 'Add Person' in empty trees, and sets non-existent Active/Home Person to the 1st created Person), then it will be more newbie-friendly than EVERY existing Charts view mode.

**Comment by emyoulation** [comment]
The ugly condition (for GUI feedback) is when there is no Tree loaded.

Serge created a couple experimental features for creating a 1st family. But both still required that the user create a new Tree, rename the Tree, and load the tree.

The only workflow that avoids that particular barrier-to-entry is when the Gramps app is closed. If you right‐click a GEDCOM file in the OS and choose Gramps as the application to Open that .ged file, then Gramps creates a new Tree, names the Tree after the GEDCOM filename, and imports the data.

**Comment by giotodibondone** [comment]
> and create a tree

My suggestion if you do this is to name the family tree after the persons name (default) or popup a dialog asking what to call the new family tree 🥇

**Comment by emyoulation** [comment]
Not exactly. I think the "Add Person" or missing person gui element when no Tree is loaded would be too ambiguous.

Instead, have an "add Missing Tree" visualization that does both the NewTree/LoadTree when no database is loaded. (They can access the Family Trees dialog from the menu istead of the visualization.) The view could detect the Tree load and switch to the "Missing Person" visualization afterwards. That would not be ambiguous. 

It is still 2 distinct steps. But advances with mouse clicks and without keyboarding until they get to the new Person dialog. (They can rename the Tree at a future date.)

The following is not your problem, but I do think the Family Trees dialog is an experiment in UI mouse/keyboarding chaos. The whole 3-step of New/Rename/Load could be a single step for the 1st tree. Especially since there are multiple spots where users can get derailed within those steps. 

(The 'new' highlights the Tree name text and disables the Load button until the name is committed. The name change is lost if you click outside instead of committing with tab or enter. The "Load" is a non-standard label and confuses some new users.)

**Comment by giotodibondone** [comment]
@emyoulation Can you open another issue and continue this so the focus is only the bug report please!

**Comment by emyoulation** [comment]
It is the same issue.

All about what to do when there is no Tree loaded (which falls back to the dummy.db to avoid general View errors) and when a loaded tree does not have the required Active Person or Home Person that this new view mode expects.

**Comment by giotodibondone** [comment]
> It is the same issue.

lol I agree yes it is, but you are talking about enhancing it with a new feature instead of just taking care of the issue in the way that the rest of the program does and adding noise.

Please don't hijack the simplest existing bug fix based on code you already pointed out!

Move the conversation to forum at least so others can input also!

**Comment by PQYPLZXHGF** [comment]
> Serge created a couple experimental features for creating a 1st family. But both still required that the user create a new Tree, rename the Tree, and load the tree.

Sounds like the feature has not been fully nutted out yet anyway!

**Comment by emyoulation** [comment]
> Sounds like the feature has not been fully nutted out yet anyway!

The 2 attempts were well intentioned but didn't capture much interest. They didn't really make things easier... just herded new users through the 1st hoops that have to be jumped. Training wheels, nit jet-assist.

**Comment by giotodibondone** [comment]
> Please check if the latest version (v0.1.15) fixes all the errors.

Tested and seems to work. Thank you

**Comment by emyoulation** [comment]
> @emyoulation I'm open for a better solution which is more intuitive for users new to Gramps. But with regard to the discussion in a separate issue or in the forum, I side with @giotodibondone. You can open a new issue or a new forum thread if you like. I would like to keep the original FamilyTreeView thread in the forum for the questions and feedback of new users of this view

I realized that such a request is not appropriate for your addon.

If someone is advanced enough to install and add-on view, they are past needing hints about Active Person, Home Person and loading trees. It would be extraneous code for your view.
